name: Build Superset lean image

on:
  push:
    branches:
      - tne-main
  pull_request:
    branches:
      - tne-main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: netdrones/superset
  TAG: ${{ github.ref_name }}-${{ github.sha }}

jobs:
  build_and_push_image:
    name: Build Docker image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: services/superset
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          target: lean
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-to: type=inline
